Sync checks on nodes
Web3-Pi/web3-reverse-proxy pull request #90
Opened 2024-08-28 07:25 UTC by lukasz-glen

Nodes that are out of sync change status to OUT_OF_SYNC and are not active until another sync test pass.

2024-09-02 19:30 UTC, shadeofblue requested changes
please see my comments

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +            req.content = b'{"method":"eth_getBlockByNumber","params":["latest",false],"id":1,"jsonrpc":"2.0"}'
```suggestion
            req = RPCRequest(
                headers = b'User-Agent: curl/8.0.1\r\nAccept: */*\r\nContent-Type: application/json\r\nContent-Length: 82\r\n'
                content = b'{"method":"eth_getBlockByNumber","params":["latest",false],"id":1,"jsonrpc":"2.0"}'
            )
```

but even better, I'd love some helper method, e.g. `RPCRequest.new()` that would take data as a dictionary and would construct the resultant `RPCRequest` object with properly initialized `headers` and `content` without having to manually submit bytestrings :/

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +            req.headers = b'User-Agent: curl/8.0.1\r\nAccept: */*\r\nContent-Type: application/json\r\nContent-Length: 82\r\n'
plus, please don't use `curl` as a user-agent, when performing your own, custom query ;) I believe it's legal to omit this header altogether... but if we do want to put it in, let's add e.g. `web3pi-proxy/[version]` or something similar...

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +class HttpResponseParserListenerSyncController:
the name is "HttpResponseParserListenerSyncController" but then it's used as a "response listener" -> shouldn't the name reflect just that? 

```suggestion
class SyncControllerResponseListener:
```

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +                    self.__logger.error(f"{self.__pool_name}: Sync test failed: reason unknown")
```suggestion
                self.__logger.error(f"{self.__pool_name}: Sync test failed: {error or 'reason unknown'}")
```

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +            if not result:
I'd raise exceptions here and catch them in one place (in the SyncController) -> then, there would be a lot less if/then/etc logic responsible mostly for logging of different responses... :/

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +        except Exception as error:
do we _really_ want to catch any and all errors here in the listener?

2024-09-02 19:30 UTC, shadeofblue commented on web3pi_proxy/core/rpc/node/endpoint_pool/pool_manager.py
> +        except Exception as error:
especially, if we're catching all errors here anyway, we would be better with just throwing regular exceptions at the listener level...

2025-01-15 13:50 UTC, mgordel approved these changes

2025-01-15 14:11 UTC, merged